name: Build wheels

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: ["3.11"]
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          # Armadillo and OpenMP
          sudo apt-get install -y libarmadillo-dev libomp-dev
          # Also make sure we have an updated pip/setuptools/wheel
          python -m pip install --upgrade pip setuptools wheel cibuildwheel pybind11
          # auditwheel (for manylinux repair)
          python -m pip install auditwheel

      - name: Install build dependencies (macOS)
        if: matrix.os == 'macOS-latest'
        run: |
          brew update
          brew install armadillo libomp
          # In case you need env vars so the compiler finds libomp, set them:
          export CXXFLAGS="-Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include"
          export LDFLAGS="-L/opt/homebrew/opt/libomp/lib -lomp"
          python -m pip install --upgrade pip setuptools wheel cibuildwheel pybind11

      - name: Build wheel
        run: |
          python setup.py bdist_wheel

      - name: Repair wheel (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p wheelhouse
          auditwheel repair dist/*.whl --plat manylinux2014_x86_64 -w wheelhouse

      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
          path: |
            dist/*.whl
            wheelhouse/*.whl


      # Test built wheels
      - name: Test built wheels
        run: |
          python -m pip install dist/*.whl
          python -c "import spheroids; print('Package imported successfully!')"
          
