name: Build Wheels

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install cibuildwheel

      # OS-specific setup
      - name: OS-specific setup
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libarmadillo-dev

      - name: OS-specific setup
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew update
          brew install armadillo

      - name: OS-specific setup
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          choco install armadillo --version=14.2.2 # Replace with correct version if available

      # Build wheels
      - name: Build wheels with cibuildwheel
        run: cibuildwheel --output-dir dist

      # Upload built wheels as artifacts
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: built-wheels
          path: dist/

