name: Build Wheels

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel cibuildwheel

      # OS-specific setup for Linux (inside manylinux2014)
      - name: Build wheels on Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          CIBW_BEFORE_BUILD: "yum install -y armadillo-devel"  # Install Armadillo in manylinux
          CIBW_MANYLINUX: manylinux2014                       # Use manylinux2014 compatibility
        run: cibuildwheel --output-dir dist

      # OS-specific setup for macOS
      - name: Build wheels on macOS
        if: ${{ matrix.os == 'macos-latest' }}
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15                    # Set macOS deployment target
        run: |
          brew update
          brew install armadillo
          cibuildwheel --output-dir dist

      # OS-specific setup for Windows
      - name: Build wheels on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          choco install armadillo --version=10.8.2  # Adjust version if necessary
          cibuildwheel --output-dir dist

      # Upload built wheels
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: built-wheels-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/

      # Test built wheels
      - name: Test built wheels
        run: |
          python -m pip install dist/*.whl
          python -c "import spheroids; print('Package imported successfully!')"
