name: Build wheels

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ["3.11"]
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          # Armadillo and OpenMP
          sudo apt-get install -y libarmadillo-dev libomp-dev
          # Also make sure we have an updated pip/setuptools/wheel
          python -m pip install --upgrade pip setuptools wheel cibuildwheel pybind11
          # auditwheel (for manylinux repair)
          python -m pip install auditwheel

      - name: Install build dependencies (macOS)
        if: matrix.os == 'macOS-latest'
        run: |
          brew update
          brew install armadillo libomp
          # In case you need env vars so the compiler finds libomp, set them:
          export CXXFLAGS="-Xpreprocessor -fopenmp -I/opt/homebrew/opt/libomp/include -I/opt/homebrew/opt/armadillo/include"
          export LDFLAGS="-L/opt/homebrew/opt/libomp/lib -lomp -L/opt/homebrew/opt/armadillo/lib"
          python -m pip install --upgrade pip setuptools wheel cibuildwheel pybind11
          
      # ---------- WINDOWS DEPENDENCIES ----------
      - name: Install build dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          # 1) Clone vcpkg into C:\vcpkg
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg

          # 2) Build vcpkg.exe
          cd C:\vcpkg
          .\bootstrap-vcpkg.bat -disableMetrics

          # 3) Install Armadillo (and any other libs) via vcpkg
          .\vcpkg.exe install armadillo

          # Upgrade pip + install cibuildwheel
          python -m pip install --upgrade pip setuptools wheel cibuildwheel pybind11
 

      - name: Build wheels with cibuildwheel
        shell: bash
        run: |
          case "${{ matrix.os }}" in
            "ubuntu-latest")
              # Linux: Install Armadillo inside the manylinux container
              export CIBW_BEFORE_BUILD_LINUX="yum install -y armadillo-devel"
              ;;
            "macOS-latest")
              # macOS: Set deployment target to match Homebrew libraries
              export MACOSX_DEPLOYMENT_TARGET=14.0
              ;;
            "windows-latest")
              echo "Windows build steps go here"
              set CXXFLAGS=/std:c++17 /openmp /I"C:\vcpkg\installed\x64-windows\include"
              set LDFLAGS=/LIBPATH:"C:\vcpkg\installed\x64-windows\lib"
              ;;
          esac
          
          export CIBW_SKIP="pp* *i686* *musllinux*"
          cibuildwheel --output-dir wheelhouse
          
      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
          path: wheelhouse/*.whl


      # Test built wheels
    #- name: Test built wheels
    #   run: |
    #     python -m pip install wheelhouse/*.whl 
    #     python -c "import spheroids; print('Package imported successfully!')"
