name: Build Wheels

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel cibuildwheel

      # OS-specific setup for Armadillo
      - name: OS-specific setup for Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libarmadillo-dev

      - name: OS-specific setup for macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew update
          brew install armadillo
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15  # Set deployment target for macOS

      - name: OS-specific setup for Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          choco install armadillo --version=10.8.2  # Adjust version if necessary

      # Build wheels with cibuildwheel
      - name: Build wheels
        env:
          CIBW_MANYLINUX: manylinux2014          # Set Linux compatibility
          MACOSX_DEPLOYMENT_TARGET: 10.15        # Set macOS deployment target
        run: cibuildwheel --output-dir dist

      # Upload built wheels
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: built-wheels-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/
      
      - name: Test built wheels
        run: |
          python -m pip install dist/*.whl
          python -c "import spheroids; print('Package imported successfully!')"


